name: todo_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  


  cupertino_icons: ^1.0.6
  dio: ^5.5.0+1
  retrofit: '>=4.0.0 <5.0.0'
  logger: any  
  hexcolor: ^3.0.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  loading_indicator: ^3.1.1
  flutter_network_connectivity: ^0.0.6
  fluttertoast: ^8.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: '>=2.3.0 <4.0.0'
  retrofit_generator: ^8.1.2
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true